notifications:
  email:
    recipients:
      - marcus.ding@student.hpi.de
    on_success: never
    on_failure: always
language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=Arduino/examples/Wemos/Wemos.ino PLATFORMIO_CI_EXTRA_ARGS="--lib=/tmp/ESPAsyncUDP --lib=/tmp/ESPTIME --lib=/tmp/FLIPDOT --lib=/tmp/Time --lib=/tmp/Timezone --board=d1_mini --board=huzzah --board=esp01"
    - PLATFORMIO_CI_SRC=Arduino/examples/Wemos_Demo/Wemos_Demo.ino PLATFORMIO_CI_EXTRA_ARGS="--lib=/tmp/Snake --lib=/tmp/ESPAsyncUDP --lib=/tmp/ESPTIME --lib=/tmp/FLIPDOT --lib=/tmp/Time --lib=/tmp/Timezone --board=d1_mini --board=huzzah --board=esp01"
    - PLATFORMIO_CI_SRC=Arduino/examples/Wemos_Snake/Wemos_Snake.ino PLATFORMIO_CI_EXTRA_ARGS="--lib=/tmp/Snake --lib=/tmp/ESPAsyncUDP --lib=/tmp/ESPTIME --lib=/tmp/FLIPDOT --lib=/tmp/Time --lib=/tmp/Timezone --board=d1_mini --board=huzzah --board=esp01"
    - PLATFORMIO_CI_SRC=Arduino/examples/Arduino_HW/Arduino_HW.ino PLATFORMIO_CI_EXTRA_ARGS="--lib=/tmp/FLIPDOT --board=uno --board=nanoatmega168 --board=nanoatmega328"
    
install:
    - pip install -U platformio
    - cp -R Arduino/ESPAsyncUDP /tmp/
    - cp -R Arduino/ESPTIME /tmp/
    - cp -R Arduino/FLIPDOT /tmp/
    - cp -R Arduino/Time /tmp/
    - cp -R Arduino/Timezone /tmp/
    - git clone https://github.com/kryptokommunist/Snake.git /tmp/Snake

script:
    - platformio ci $PLATFORMIO_CI_EXTRA_ARGS
